nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['OPTIONS', 'GET', 'POST']
        max_age: 3600
        allow_credentials: false
    paths:
        '^/api/': ~
